### ISSUE TITLE
Datasets missing

### ISSUE THREAD

**Issue by iaOlivia** [Sriram-Ravula/MRI_Sampling_Diffusion#1]
Hi Sriram,
 train_input_dir: '/csiNAS/brett/sites_new/Training/site5/ksp'
 train_maps_dir: '/csiNAS/brett/sites_new/Training/site5/maps'
 test_input_dir: '/csiNAS/brett/sites_new/Validation/site5/ksp'
 test_maps_dir: '/csiNAS/brett/sites_new/Validation/site5/maps'
above data you didn't provide for the project

**Comment by Sriram-Ravula** [comment]
Hello, thanks for raising this issue. The data stored at those directories is the fastMRI multi-coil brain and knee scan data. Due to the large size of the dataset as well as the usage agreement required by fastMRI, I can't provide that data. You can go to the fastMRI website at [https://fastmri.med.nyu.edu/](https://fastmri.med.nyu.edu/) and request access to obtain the dataset.

**Comment by iaOlivia** [comment]
Thank you for solving my question. I will go to the website you share with me and try my best to get these data.Thank you again!

**Comment by iaOlivia** [comment]
<img width="225" alt="image" src="https://github.com/Sriram-Ravula/MRI_Sampling_Diffusion/assets/94520452/72d3cb89-ca22-4569-b75c-71d18732b080">
Can you pls tell me which one used in training so I can download corresponding one.

**Comment by iaOlivia** [comment]
<img width="225" alt="image" src="https://github.com/Sriram-Ravula/MRI_Sampling_Diffusion/assets/94520452/72d3cb89-ca22-4569-b75c-71d18732b080">
Can you pls tell me which one used in training so I can download corresponding one.

**Comment by Sriram-Ravula** [comment]
You should download knee_multicoil_train_batch_0, knee_multicoil_val, brain_multicoil_train_batch_0, and brain_multicoil_val_batch_0

**Comment by iaOlivia** [comment]
After unzip i get some .h5 files.How to divide them into ksp and maps like used in code.
Seems it missing the maps file , coule you please tell where to download them
